### ISSUE TITLE
iohook reported error on nwjs: Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by Erdong3ye** [wilix-team/iohook#101]
When I installed the iohook-v0.2.0 module successfully in the nwjs SDK package using "npm install iohook -- save", but when I double-clicked to run nw.exe, the console reported the following error:
Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:749:18)
    at Module.load (internal/modules/cjs/loader.js:613:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:552:12)
    at Function.Module._load (internal/modules/cjs/loader.js:544:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\E\nwjs-sdk-v0.30.5-win-x64 - iohook-test2\node_modules\iohook\index.js:16:21)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:719:10)
    at Module.load (internal/modules/cjs/loader.js:613:32)

My expectation is that when I run nw.exe, iohook will work and output my keyboard and mouse behavior as required.
But after running the console reported the above error and iohook could not be used.

The following is a screenshot of my code, including the error output after running:
![2](https://user-images.githubusercontent.com/31117941/45464485-5d407f80-b743-11e8-8f31-267b16e7712c.png)

This problem makes me unable to use iohook, and the next work can not be carried out. I've spent two weeks looking for solutions online, and the results have not changed. I hope you can offer some help.

My running environment:

nw.js:0.30.2/0.30.5/0.33.2 (all three versions have tried and reported the same error).

node.js:10.0.0;

npm:5.6.0;

yarn:1.9.4 (also tried to use "yarn add iohook", but still reported the same error).

Win10-64;

Thank you!

**Comment by Djiit** [comment]
Hi there, in order to use it with NW, you will have to compile iohook yourself for this target. Sadly I can't help you with that, I don't know the corresponding target.

**Comment by Erdong3ye** [comment]
I am sorry that I failed to reply to you in time because I had a business trip some time ago.

This is my first contact with nwjs, so how do I compile it?

Do I need to upload the project files to you?

**Comment by Djiit** [comment]
Closing this as this was related to a previous, outdated iohook version. Feel free to reopen it.
