### ISSUE TITLE
Installation fails on debian buster 32bit

### ISSUE THREAD

**Issue by traumschule** [wilix-team/iohook#112]
Hi! Unfortunately iohook fails to install here.

## Expected Behavior
Installation succeeds.

## Current Behavior
```
$ npm install iohook --save

> segfault-handler@1.0.1 install /home/user/tbb-manual-image-creator/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/home/user/tbb-manual-image-creator/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
In file included from /home/user/.node-gyp/8.12.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/segfault-handler.cpp:2:
/home/user/.node-gyp/8.12.0/include/node/v8.h: In static member function ‘static void v8::V8::SetAllowCodeGenerationFromStringsCallback(v8::DeprecatedAllowCodeGenerationFromStringsCallback)’:
/home/user/.node-gyp/8.12.0/include/node/v8.h:10311:19: warning: cast between incompatible function types from ‘v8::DeprecatedAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v
8::Context>)’} to ‘v8::FreshNewAllowCodeGenerationFromStringsCallback’ {aka ‘bool (*)(v8::Local<v8::Context>, v8::Local<v8::String>)’} [-Wcast-function-type]
           callback));
                   ^
/home/user/.node-gyp/8.12.0/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCPrologueCallback(v8::GCCallback)’:
/home/user/.node-gyp/8.12.0/include/node/v8.h:10356:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolat
e::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<Isolate::GCCallback>(callback));
                                                     ^
/home/user/.node-gyp/8.12.0/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCEpilogueCallback(v8::GCCallback)’:
/home/user/.node-gyp/8.12.0/include/node/v8.h:10363:53: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolat
e::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<Isolate::GCCallback>(callback));
                                                     ^
In file included from ../src/segfault-handler.cpp:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2208:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-fun
ction-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../../nan/nan.h:52,
                 from ../src/segfault-handler.cpp:2:
../src/segfault-handler.cpp: At global scope:
/home/user/.node-gyp/8.12.0/include/node/node.h:505:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::O
bject>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/user/.node-gyp/8.12.0/include/node/node.h:536:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/segfault-handler.cpp:339:3: note: in expansion of macro ‘NODE_MODULE’
   NODE_MODULE(segfault_handler, init)
In file included from /home/user/.node-gyp/8.12.0/include/node/node.h:63,                                                                                                                      
                 from ../../nan/nan.h:52,
                 from ../src/segfault-handler.cpp:2:                                                                                                                                                  
/home/user/.node-gyp/8.12.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/user/.node-gyp/8.12.0/include/node/node_object_wrap.h:85:78:   required from here
/home/user/.node-gyp/8.12.0/include/node/v8.h:9307:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);                                                                                                                                          
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/.node-gyp/8.12.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::Obj
ectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:                                                                       
../../nan/nan_object_wrap.h:66:61:   required from here                                                                                                                                               
/home/user/.node-gyp/8.12.0/include/node/v8.h:9307:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCal
lbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]                                                                               
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory '/home/user/tbb-manual-image-creator/node_modules/segfault-handler/build'                                                                             

> iohook@0.2.1 install /home/user/tbb-manual-image-creator/node_modules/iohook                                                                                                
> node install.js

Downloading prebuild for platform: iohook-v0.2.1-node-v57-linux-ia32
Prebuild for current platform (iohook-v0.2.1-node-v57-linux-ia32) not found!
Try to compile for your platform:
# cd node_modules/iohook;
# npm run compile


/home/user/tbb-manual-image-creator/node_modules/iohook/install.js:14
  throw err;
  ^
Prebuild for current platform (iohook-v0.2.1-node-v57-linux-ia32) not found!
npm WARN tbb-manual-image-creator@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iohook@0.2.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iohook@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Possible Solution
No idea, sorry :/

## Steps to Reproduce (for bugs)
`npm i iohook`

## Context
```
git clone https://github.com/arthuredelstein/tbb-manual-image-creator
cd tbb-manual-image-creator
npm i
```
See README.md for additional dependencies.

## Your Environment
* Version used: npm 6.4.1
* Environment name and version: node v8.12.0
* Operating System and version: debian buster 32bit
> 4.18.0-1-686 #1 SMP Debian 4.18.6-1 (2018-09-06) i686 GNU/Linux
* Link to your project: https://github.com/arthuredelstein/tbb-manual-image-creator

Thanks for your work!

**Comment by Djiit** [comment]
Hi there, this is obviosuly an error with segfault-handler as stated in your logs. What we could do is provide prebuilt binaries for linux 32b. Let me check that.

**Comment by Djiit** [comment]
Could you retry now ?

**Comment by traumschule** [comment]
Thanks for the fast repsonse!
```
iohook$ git pull
Updating a0bc5bc..371f821
Fast-forward
 .travis.yml                               |   15 +-
 CHANGELOG.md                              |    8 +
 build.js                                  |    8 +-
 install.js                                |    2 +-
 libuiohook/src/darwin/input_helper.c      |   67 +-
 libuiohook/src/darwin/input_hook.c        |   84 +-
 libuiohook/src/darwin/system_properties.c |  248 ++--
 package-lock.json                         | 9766 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------
 package.json                              |    6 +-
 9 files changed, 5853 insertions(+), 4351 deletions(-)

iohook$ npm i
npm WARN tar write after end
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by traumschule** [comment]
```
node -e "console.log (process.arch)" => ia32
node -e "console.log (process.platform)" => linux
```
It tries to download _https://github.com/WilixLead/iohook/releases/download/v0.2.3/iohook-v0.2.3-node-v57-linux-ia32.tar.gz_ but there are only _https://github.com/WilixLead/iohook/releases/download/v0.2.3/iohook-v0.2.3-node-v57-linux-x32.tar.gz_ and _https://github.com/WilixLead/iohook/releases/download/v0.2.3/iohook-v0.2.3-node-v57-win32-ia32.tar.gz_.

**Comment by Djiit** [comment]
Hi there,
Yeah it seems like a "simple" naming issue. "ia32" / "x32". i'll try to find some time this weekend to investigate this.

**Comment by traumschule** [comment]
Great! With
```
diff --git a/install.js b/install.js
index 4352348..efa8b77 100644
--- a/install.js
+++ b/install.js
@@ -23,13 +23,14 @@ function onerror(err) {
  * @param cb Callback
  */
 function install(runtime, abi, platform, arch, cb) {
+  if (arch = "ia32") { arch = "x32"; }
   const essential = runtime + '-v' + abi + '-' + platform + '-' + arch;
```
i get
```
npm audit fix
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

updated 5 packages in 70.242s
fixed 10 of 14 vulnerabilities in 29685 scanned packages
  2 package updates for 4 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually
```
and with `npm audit fix --force`
```
npm WARN using --force I sure hope you know what you are doing.

> fsevents@1.2.4 install /media/user/traumschule/tor/manual/iohook/node_modules/fsevents
> node install

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.                                                                         

+ cmake-js@4.0.1
added 71 packages from 26 contributors and updated 4 packages in 138.626s
fixed 1 of 1 vulnerability in 29718 scanned packages
  1 package update for 1 vuln involved breaking changes
  (installed due to `--force` option)
```
Our project installs now. Thanks for your help!

**Comment by Djiit** [comment]
Great ! Could you retry without your modifications now ? 0.2.3 binaries are available for linux-ia32

**Comment by traumschule** [comment]
For some reason it downloads a 64bit file.
```
$ rm -r node_modules/iohook/
$ npm i 

> iohook@0.2.3 install /home/user/src/tbb-manual-image-creator/node_modules/iohook
> node install.js

Downloading prebuild for platform: iohook-v0.2.3-node-v57-linux-ia32
npm WARN tbb-manual-image-creator@0.0.1 No repository field.

added 1 package from 1 contributor and audited 613 packages in 7.71s
found 0 vulnerabilities

$ npm start

> tbb-manual-image-creator@0.0.1 start /home/user/src/tbb-manual-image-creator
> node index.js

module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /home/user/src/tbb-manual-image-creator/node_modules/iohook/builds/node-v57-linux-ia32/build/Release/iohook.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/src/tbb-manual-image-creator/node_modules/iohook/index.js:16:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tbb-manual-image-creator@0.0.1 start: `node index.js`
npm ERR! Exit status 1

$ file -b /home/user/src/tbb-manual-image-creator/node_modules/iohook/builds/node-v57-linux-ia32/build/Release/iohook.node
ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f67ddccd25e0f3891f60083332b9b26e04024c98, not stripped
```

**Comment by Djiit** [comment]
I'm a bit stuck here. Does anyone knows how to properly build for linux-ia32 ?
I'm beginning to think it never worked before.

**Comment by ash0x0** [comment]
Closed as irrelevant. Not sure if this is an issue anymore but if so (highly doubtful) it should be addressed after we transition to a local build instead of prebuilds.
