### ISSUE TITLE
Error: ***/iohook.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by uzervlad** [wilix-team/iohook#139]
## Expected Behavior
Well, it should've ran at least ¯\\\_(ツ)_/¯

## Current Behavior
It stops with this error:
```
module.js:670
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\xxx\node_modules\iohook\builds\node-v59-win32-ia32\build\Release\iohook.node is not a valid Win32 application.
\\?\D:\xxx\node_modules\iohook\builds\node-v59-win32-ia32\build\Release\iohook.node
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\xxx\node_modules\iohook\index.js:10:21)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```

## Your Environment
* Version used: 0.3.1
* Environment name and version: NodeJS v9.2.0
* Operating System and version (desktop or mobile): Windows 8.1 x32

**Comment by Djiit** [comment]
Hey @uzervlad , still experiencing this ?

**Comment by uzervlad** [comment]
Yeah, now it works great. Thank you!

**Comment by Djiit** [comment]
Glad to here it, thanks !

**Comment by gigmelepcha** [comment]
@uzervlad can you tell me how it is working ?
I am stuck with the same issue 
my package
`"iohook": {
    "arches": [
    "x64"
    ],
    "platforms": [
    "win32",
    "darwin",
    "linux"
    ],
     "targets": [
      "electron-101",
      "node-93"
    ]
  },`
