### ISSUE TITLE
Windows Electron DLL initialization Error

### ISSUE THREAD

**Issue by danthegoodman1** [wilix-team/iohook#165]
So i've followed all of the steps of configuring my package.json:

```
"iohook": {
    "targets": [
      "node-64",
      "electron-64"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }
```

and:

```
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "3.1.9"
  },
```

I've also tried using electron-rebuild:

`.\node_modules\.bin\electron-rebuild.cmd -f`

Here is the error output:

```
 ELECTRON_ASAR.js:166
[1]         return old.apply(this, arguments)
[1]                    ^
[1]
[1] Error: A dynamic link library (DLL) initialization routine failed.
[1] \\?\C:\Users\Dan\Desktop\registrationutilities\node_modules\iohook\builds\node-v64-win32-x64\build\Release\iohook.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
[1]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
[1]     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
[1]     at Module.load (internal/modules/cjs/loader.js:620:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
[1]     at Module.require (internal/modules/cjs/loader.js:658:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (C:\Users\Dan\Desktop\registrationutilities\node_modules\iohook\index.js:10:21)
    at Object.<anonymous> (C:\Users\Dan\Desktop\registrationutilities\node_modules\iohook\index.js:397:3)
[1] refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 1 layouts.
[1] refresh_locale_list [493]: Received 1 locales.
[1] load_input_helper [866]: refresh_locale_list() found 1 locale(s).
```

## Expected Behavior
I shouldn't get this error

## Current Behavior
I get this error

## Steps to Reproduce (for bugs)
1. Install with configuration in package.json
2. Fork a node.js file from the electron process, with iohook required in the forked file

## Context
Everything else SEEMS to run fine, but not the forked process

## Your Environment
* Version used: 0.4.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node 10.15.3, Electron 3.1.9 (these were the only versions I could use together without having iohook require a higher version of the node-XXv that actually existed)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: N/A

**Comment by danthegoodman1** [comment]
I'd also note that the reason I am using electron `3.1.9` is because when specifying `node-XXV` and `electron-XXv` it would look for the node version of what ever the installed electron version ended up being, weird I know

**Comment by danthegoodman1** [comment]
If I do try to use electron `4.2.0`, I get this error instead: ```
internal/modules/cjs/loader.js:586
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'C:\Users\Dan\Desktop\registrationutilities\node_modules\iohook\builds\node-v69-win32-x64\build\Release\iohook.node'
```

**Comment by danthegoodman1** [comment]
FIXED IT. Turns out it was just because I was forking the process that was using it, but I am still forced to use electron 3.1.9 with node 10.15.3... Good enough for me though. I'll leave this open so maybe someone can look at the version forcing issue...

**Comment by Djiit** [comment]
Seems like your electron version combo is wrong :
 `"electron-64" + "runtimeVersion": "3.1.9"` doesn't make sense. Try not to specify the cmakejs version, or use 4.1.1 for instance.

**Comment by Djiit** [comment]
I'm closing this. Feel free to tell us if you still experience this.

**Comment by karacas** [comment]
Maybe this help:
[https://github.com/wilix-team/iohook/issues/160](url)
