### ISSUE TITLE
MacOS: Iohook crashes when electron application is signed with certificates

### ISSUE THREAD

**Issue by staticbass** [wilix-team/iohook#184]
When I'm running my application the exception is thrown when I require `iohook` module. It happens only if I sign it with certificates. If I skip signing step everything works just fine. 

## Expected Behavior
No exception is thrown

## Current Behavior
Such exception is thrown when I require `iohook`:
```
Error: dlopen(/var/folders/ys/rqhxzkss6r9c7wr7c6j82gbc0000gn/T/.my.app.name.RH9ywq, 1): no suitable image found.  Did find:
	/var/folders/ys/rqhxzkss6r9c7wr7c6j82gbc0000gn/T/.my.app.name.RH9ywq: code signature in (/var/folders/ys/rqhxzkss6r9c7wr7c6j82gbc0000gn/T/.my.app.name.RH9ywq) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/var/folders/ys/rqhxzkss6r9c7wr7c6j82gbc0000gn/T/.my.app.name.RH9ywq: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Object.func [as .node] (electron/js2c/asar.js:164:18)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Applications/App Name.app/Contents/Resources/app.asar/node_modules/iohook/index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:815:30)
```

Configuration in package.json:
```
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "5.0.2"
  },
  "iohook": {
    "targets": [
      "node-64",
      "electron-70"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
```

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Export certificates 
```
export CSC_LINK=./Developer\ ID\ Application.p12
export CSC_KEY_PASSWORD=<<cert-password>>
```
2. Build app
```
$(npm bin)/electron-builder --x64 --macos
```
3. Open app

## Your Environment

* Version used: 0.4.6 and 0.5.1
* Environment name and version: Node 10.16.0; Electron 5.0.2
* Operating System: macOS Mojave 10.14.5

**Comment by staticbass** [comment]
Building on CI server fixed the issue

**Comment by isstep** [comment]
Hi @staticbass, I've encountered same problem "code signature not valid".
I'm using pre-build for node-v57-darwin-x64 for Premiere Pro.
PPro 2019 works fine, recently released PPro 2020 gives that error.

Can you tell more about how you fixed it?

**Comment by staticbass** [comment]
Hi @isstep, 
The solution was to move build and sign steps to CircleCI with same electron builder config.

**Comment by sir-editor** [comment]
Thank you!
