### ISSUE TITLE
iohook not working windows

### ISSUE THREAD

**Issue by sample-text-here** [wilix-team/iohook#249]
Running `const ioHook = require("iohook");` doesn't work, even if that's the only thing in the file

Using
* Windows 10
* Node 12.18.3
* WSL Ubuntu 20.04
* pnpm 5.5.7

## Expected Behavior
Loads iohook

## Current Behavior
```
internal/modules/cjs/loader.js:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/c/Users/bagle/OneDrive/Desktop/coding junk/ocr/node_modules/.pnpm/iohook@0.6.6/node_modules/iohook/index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

## Steps to Reproduce (for bugs)
1. `pnpm init`
2. `pnpm i iohook`
3. Put in index.js: `const ioHook = require("iohook");`
5. `node index.js`
6. Watch your hopes and dreams get destroyed

## Context
- Trying to listen for keyboard shortcuts
- Testing iohook to make sure it works
- Why doesn't it work
- Is it a bug in WSL
- Trying to do OCR on clipboard photo on shortcut
- Maybe it's pnpm

## Your Environment
See above

**Comment by matthew-plusprogramming** [comment]
Same issue here

**Comment by abhijit-hota** [comment]
> Same issue here (although not sure if this can be done since WSL is a virtual machine)

Do you mean it can't/won't be fixed for WSL?!

Also which issue do you mean by _same issue here_. #268 ?

**Comment by abhijit-hota** [comment]
Update: Take a look at this issue I mentioned. 
Specifically the discussion since [this comment](https://github.com/wilix-team/iohook/issues/268#issuecomment-751437757):

**Comment by ash0x0** [comment]
Closing as resolved.
