### ISSUE TITLE
problems with keydown event

### ISSUE THREAD

**Issue by Andyloris** [wilix-team/iohook#278]
when i run this code: 
`var bfexec = require('execute-bf-code')
var iohook = require('iohook')
var robot = require('robotjs')

iohook.on("keydown", event => {
    string_to_type = bfexec.execute_code('dvorak.b', true, "", String.fromCharCode(event.keycode))
    robot.typeString(string_to_type)
})
iohook.start()`

with this file called 'dvorak.b' in my folder: 

[dvorak.zip](https://github.com/wilix-team/iohook/files/5720000/dvorak.zip)

 i have this error:
events.js:345
  events = target._events;
                  ^

TypeError: Cannot read property '_events' of undefined
    at _addListener (events.js:345:19)
    at addListener (events.js:401:10)
    at Object.execute_code (C:\Users\Someone\Desktop\calc_pi_bf\node_modules\execute-bf-code\main.js:32:5)
    at IOHook.<anonymous> (C:\Users\Someone\Desktop\calc_pi_bf\index.js:7:29)
    at IOHook.emit (events.js:310:20)
    at IOHook._handler (C:\Users\Someone\Desktop\calc_pi_bf\node_modules\iohook\index.js:211:12)

Someone have a fix ?

Thanks in avance !

**Comment by ash0x0** [comment]
According to the stacktrace, this issue happens in `execute-bf-code\main.js:32:5`, not in iohook. Closing. Please reopen if this issue is relevant or in case of something similar.
