### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PxlLoewe** [wilix-team/iohook#331]
Hi,
when trying to install your package, it throws this error: 

![image](https://user-images.githubusercontent.com/72106766/120536259-355a4400-c3e4-11eb-9047-422615405375.png)

**Comment by Rabyt** [comment]
npm install iohook@0.9.0 worked for me

**Comment by PxlLoewe** [comment]
> npm install iohook@0.9.0 worked for me

Thank you so much! I did a lot of research, but din´t find a solution. But now, the electron compiler does not find the build for the current electron/node version. Do I need to downgrade both? Wich versions do you use? Thank you again!

App threw an error during load
Error: Cannot find module 'E:\Dev\vHEMS_v2\client\electron-app\node_modules\iohook\builds\electron-v87-win32-x64\build\Release\iohook.node'
Require stack:
- E:\Dev\vHEMS_v2\client\electron-app\node_modules\iohook\index.js
- E:\Dev\vHEMS_v2\client\electron-app\main.js
- E:\Dev\vHEMS_v2\client\electron-app\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Dev\vHEMS_v2\client\electron-app\node_modules\iohook\index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)

**Comment by ash0x0** [comment]
Seems solved, closing. For future reference until `v0.9.2` is released: `v0.9.1` will not install on windows so use `v0.9.0` for windows and `v0.9.1` on linux and mac. This is a prebuilds issue and you can either get around it by specifying version depending on your OS or building yourself. This will be resolved very soon.
