### ISSUE TITLE
build failed for electron 13 (abi 89) 

### ISSUE THREAD

**Issue by ceonizm** [wilix-team/iohook#339]
Hello, 

I was trying to build iohook on my local computer for electron 13.1.2 by running 

`node build.js --runtime electron --abi 89 --version 13.1.2 --no-upload
`
and node-gyp has finished by a not OK 

`> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/home/ceone/workspace/iohook/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
> gyp ERR! System Linux 5.4.0-74-generic
> gyp ERR! command "/usr/bin/node" "/home/ceone/workspace/iohook/node_modules/.bin/node-gyp" "configure" "rebuild" "--target=13.1.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--v8_enable_pointer_compression=1" "--build_v8_with_gn=false" "--enable_lto=false"
> gyp ERR! cwd /home/ceone/workspace/iohook
> gyp ERR! node -v v12.22.1
> gyp ERR! node-gyp -v v7.1.2
> gyp ERR! not ok 
`

## Expected Behavior
Obviously I expected 
`
gyp info ok
`
at the end of the process.

I've tested and managed to build 11.x and 12.x with the same process 

Environment
ubuntu 20.04 - node 12.22.11 
tested with the latest 0.9.3 and from the git repository too

please find attached the output and error of build processes redirected to a file:
 
[abi-87-12.0.11.log](https://github.com/wilix-team/iohook/files/6649647/abi-87-12.0.11.log)
[abi-89.log](https://github.com/wilix-team/iohook/files/6649648/abi-89.log)

**Comment by ash0x0** [comment]
This is unfortunately the state for 13, there are more issues using iohook in electron 13 that even when it does build it breaks in runtime.
I'm working on the changes necessary for electron 13 and 14 but there need to be some changes to the addon first for that to happen so it's the third item on my agenda.

**Comment by geniusmonir** [comment]
I have build for node 14 and electron 13 works on development but not after build.

[iohook-v0.9.3-electron-v89-win32-x64.tar.gz](https://github.com/wilix-team/iohook/files/7112391/iohook-v0.9.3-electron-v89-win32-x64.tar.gz)
[iohook-v0.9.3-node-v83-win32-x64.tar.gz](https://github.com/wilix-team/iohook/files/7112392/iohook-v0.9.3-node-v83-win32-x64.tar.gz)

asar: true
![with asar](https://user-images.githubusercontent.com/64084419/132142165-fab935a9-4347-4218-9754-4b3ec9be0f90.JPG)

asar: false
![without asar](https://user-images.githubusercontent.com/64084419/132142170-57c2de9e-47e0-4430-9c73-6f64bb84040f.JPG)
