### ISSUE TITLE
iohook.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by Kazuy1** [wilix-team/iohook#348]
## Current Behavior

When you start the program
```
App threw an error during load
Error: C:\iohook-test\node_modules\iohook\builds\electron-v89-win32-x64\build\Release\iohook.node is not a valid Win32 application.
C:\iohook-test\node_modules\iohook\builds\electron-v89-win32-x64\build\Release\iohook.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\iohook-test\node_modules\iohook\index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```
It will be displayed.

The package.json contains the correct Node/Electron ABI version

## Steps to Reproduce (for bugs)

1.  Clone https://github.com/Kazuy1/iohook-test
2.  Run script/cleanup (run in the script folder)
3.  Start electron (electron main.js)

## Context

The source code uses the same as the [sample code](https://github.com/wilix-team/iohook/tree/master/examples/electron-main)  of iohook

## Your Environment
- Microsoft Windows 10 Pro  v10.0.19042
- IOHook Version: 0.9.3
- Environment name and version (e.g. Chrome 39, node.js 5.4, electron 11.2): node.js 14.17.3, electron 13.1.9
- Operating System and version (desktop or mobile):desktop
- Optional Link to your project: https://github.com/Kazuy1/iohook-test

**Comment by Kazuy1** [comment]
PS: Running abi.js will change the iohook abi in package.json to the Node/electron abi

**Comment by vjpr** [comment]
Same issue - any update?

**Comment by gigmelepcha** [comment]
Any update on this ?
I am using electron  : "15.3.0" abi 98
Do we have to manually do the build for win32?

**Comment by SuperJumpBros** [comment]
Still no updates in a month. I want to ditch iohook entirely, but there's nothing better to use.
