### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by bryiac** [wilix-team/iohook#367]
## Expected Behavior
For the native module to be imported properly

## Current Behavior
```
Error: The specified module could not be found.
\\?\C:\Users\User\Desktop\key\.webpack\main\native_modules\builds\electron-v85-win32-x64\build\Release\iohook.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object../node_modules/iohook/index.js (C:\Users\User\Desktop\key\.webpack\main\index.js:940:21)
    at __webpack_require__ (C:\Users\User\Desktop\key\.webpack\main\index.js:1794:42)
```

Note i have tried messing with multiple versions of node, electron and iohook 

## Possible Solution
Not sure what the solution would be as i have read through a bunch of issues opened and closed tried some of the solutions but to no avail its still giving me the same error

## Steps to Reproduce (for bugs)

1. Use electron-forge `Webpack + Typescript` template
2. Install `@electron-forge/plugin-auto-unpack-natives`
3. Run `yarn run start`
4. Receive the `Error: The specified module could not be found.` error.

## Context
Trying to make an electron app which customizable keybinds to do an action have actually tried doing this about a year ago as well but with no avail iohook still doesnt work for me

## Your Environment

- IOHook Version: v0.9.3
- Environment name and version (e.g. Chrome 39, node.js 5.4, electron 11.2):  Node: v12.22.6, Electron: v11.5.0
- Operating System and version (desktop or mobile): Version 21H1 (OS Build 19043.1237)
- Optional Link to your project: None

**Comment by coloredwax** [comment]
Another note is i do have [vc_redist.x64.exe](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) installed
