### ISSUE TITLE
iohook.node is not a valid Win32 application

### ISSUE THREAD

**Issue by schwarzsky** [wilix-team/iohook#377]
## Expected Behavior

Code is basically this, so program should log keys i pressed.
``
const ioHook = require('iohook');

ioHook.on("keyup",function(keyPress){
    console.log(keyPress)
});

ioHook.start();
``

## Current Behavior

Electron app exits with that error, it says "iohook.node is not a valid Win32 application."

```
Error: \\?\C:\Users\koray\Documents\emojithing\node_modules\iohook\builds\electron-v89-win32-x64\build\Release\iohook.node ge├ğerli bir Win32 uygulamas├¢ de├░il.
\\?\C:\Users\koray\Documents\emojithing\node_modules\iohook\builds\electron-v89-win32-x64\build\Release\iohook.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\koray\Documents\emojithing\node_modules\iohook\index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

## Your Environment

- IOHook Version: 0.9.3
- Environment name and version (e.g. Chrome 39, node.js 5.4, electron 11.2):  NodeJS 15.9.0, Electron 13.0.0
- Operating System and version (desktop or mobile): Windows 11 x64

**Comment by SuperJumpBros** [comment]
iohook team, PLEASE give us an update on this!

**Comment by dement6d** [comment]
Experiencing the same issue here with `node-v93-win32-x64` 4 months after this issue was opened
Opened another one at https://github.com/wilix-team/iohook/issues/402

**Comment by schwarzsky** [comment]
Looks like `iohook`'s creator has no time to dedicate for maintaining `iohook`.

We will wait for new maintainers if they come.

https://github.com/wilix-team/iohook/issues/291
