### ISSUE TITLE
Failed Manual Build: Missing Input Files

### ISSUE THREAD

**Issue by jove0610** [wilix-team/iohook#388]
## Expected Behavior
Everything will be okay if I run `npm run build` in ~/my_app/node_modules/iohook path

## Current Behavior
This is the terminal logs when I run `npm run build`

```
> iohook@0.9.3 build
> node build.js --upload=false

Building iohook for node v16.13.1>>>>
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.13.1 | win32 | x64
gyp info find Python using Python version 3.10.1 found at "C:\Users\User\AppData\Local\Programs\Python\Python310\python3.exe"
gyp info find VS using VS2017 (15.9.28307.1800) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
(node:2328) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn C:\Users\User\AppData\Local\Programs\Python\Python310\python3.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\system_properties.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\include\uiohook.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\post_event.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_hook.c
gyp info find Python using Python version 3.10.1 found at "C:\Users\User\AppData\Local\Programs\Python\Python310\python3.exe"
gyp info find VS using VS2017 (15.9.28307.1800) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\User\AppData\Local\Programs\Python\Python310\python3.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_hook.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\system_properties.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\post_event.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\include\uiohook.h
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  logger.c
c1 : fatal error C1083: Cannot open source file: '..\libuiohook\src\logger.c': No such file or directory [C:\Users\User\Desktop\my-app\node_modules\iohook\build\uiohook.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\Desktop\my-app\node_modules\iohook\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\Desktop\\my-app\\node_modules\\iohook\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "rebuild" "--target=16.13.1" "--arch=x64" "--v8_enable_pointer_compression=1" "--msvs_version=2017"
gyp ERR! cwd C:\Users\User\Desktop\my-app\node_modules\iohook
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
Error: Failed to build...
    at ChildProcess.<anonymous> (C:\Users\User\Desktop\my-app\node_modules\iohook\build.js:188:23)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```
## Possible Solution
not really sure....

## Steps to Reproduce (for bugs)
I use iohook on my electron app. I tried to reproduce it with fresh install of electron. This is the exact step-by-step that I did. I already did the required msys2 installation.

```
npx create-electron-app@latest my-app
// cd to my-app
npm i iohook
// cd to node_modules/iohook
npm i
npm run build
```
I also tried to delete the node_modules on iohook directory before running npm i, still the same.

## Context
I wanted to use the latest version of electron. Right now, I'm using electron v12 and wanted to move to v17. Same with node, I'm not using v14 and wanted to move to v16.

## Your Environment
- IOHook Version: 0.9.3
- Environment name and version: node.js 16.13.1, electron 17.1.0
- Operating System and version (desktop or mobile): Windows 10

## Others
Another thing is, if I clone v0.9.3 in this github repo to my pc, I can run `npm i` and `npm run build` no problem

**Comment by marcelblum** [comment]
Yeah build only works if you clone the whole repo because it includes dependencies that don't get installed from a regular `npm i iohook`. You can just copy your successful build files into node_modules/iohook.

**Comment by jove0610** [comment]
I still got an error. I copy the build folder in the github clone repo and paste it into node_modules/iohook... When I run `npm start` I got this:

```
> my-app@1.0.0 start
> electron-forge start

✔ Checking your system
✔ Locating Application
                                      Warning: Missing input files:
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\include\uiohook.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.h
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_hook.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\post_event.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\system_properties.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\windows\input_helper.c
C:\Users\User\Desktop\my-app\node_modules\iohook\build\..\libuiohook\src\logger.h
⠧ Preparing native dependencies: 0 / 1Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
⠋ Preparing native dependencies: 0 / 1  logger.c
⠙ Preparing native dependencies: 0 / 1c1 : fatal error C1083: Cannot open source file: '..\libuiohook\src\logger.c': No such file or dire
ctory [C:\Users\User\Desktop\my-app\node_modules\iohook\build\uiohook.vcxproj]
✖ Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild 'C:\Users\User\Desktop\my-app\node_modules\iohook'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1


Error: node-gyp failed to rebuild 'C:\Users\User\Desktop\my-app\node_modules\iohook'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1


    at NodeGyp.rebuildModule (C:\Users\User\Desktop\my-app\node_modules\electron-rebuild\src\module-type\node-gyp.ts:129:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\User\Desktop\my-app\node_modules\electron-rebuild\src\module-rebuilder.ts:93:5)
    at ModuleRebuilder.rebuild (C:\Users\User\Desktop\my-app\node_modules\electron-rebuild\src\module-rebuilder.ts:129:8)
    at Rebuilder.rebuildModuleAt (C:\Users\User\Desktop\my-app\node_modules\electron-rebuild\src\rebuild.ts:203:9)
    at Rebuilder.rebuild (C:\Users\User\Desktop\my-app\node_modules\electron-rebuild\src\rebuild.ts:158:9)
    at C:\Users\User\Desktop\my-app\node_modules\@electron-forge\core\src\util\rebuild.ts:38:5
```

## What I did to make the build successful (but has error on npm start)
What I then did is delete the iohook in the node_moduels of my app, then I did the git clone there. So basically the node_modules/iohook is straight from this github repo. I was then able to run `npm i ` and `npm run build` successfully. But then I got this error when I run `npm start`:

```
> my-app@1.0.0 start
> electron-forge start

✔ Checking your system
✔ Locating Application
⠇ Preparing native dependencies: 0 / 1Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
                                        logger.c
⠙ Preparing native dependencies: 0 / 1  input_helper.c
⠋ Preparing native dependencies: 0 / 1  input_hook.c
⠴ Preparing native dependencies: 0 / 1  post_event.c
⠙ Preparing native dependencies: 0 / 1  system_properties.c
⠧ Preparing native dependencies: 0 / 1  win_delay_load_hook.cc
⠼ Preparing native dependencies: 0 / 1     Creating library C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\uiohook.lib an
  d object C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\uiohook.exp
⠋ Preparing native dependencies: 0 / 1  uiohook.vcxproj -> C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\\uiohook.dll
⠹ Preparing native dependencies: 0 / 1  iohook.cc
⠹ Preparing native dependencies: 0 / 1c:\users\user\.electron-gyp\17.1.0\include\node\v8-script.h(232): warning C4996: 'v8::Module::Resol
veCallback': Use ResolveModuleCallback [C:\Users\User\Desktop\my-app\node_modules\iohook\build\ioho
ok.vcxproj]
  c:\users\user\.electron-gyp\17.1.0\include\node\v8-script.h(214): note: see declaration of 'v8::M
  odule::ResolveCallback'
⠸ Preparing native dependencies: 0 / 1c:\users\user\desktop\my-app\node_modules\iohook\src\iohook.cc(489): warning C4996: 'Nan::Callback:
:Call': was declared deprecated [C:\Users\User\Desktop\my-app\node_modules\iohook\build\iohook.vcxp
roj]
  c:\users\user\desktop\my-app\node_modules\iohook\node_modules\nan\nan.h(1744): note: see declarat
  ion of 'Nan::Callback::Call'
⠋ Preparing native dependencies: 0 / 1  win_delay_load_hook.cc
⠴ Preparing native dependencies: 0 / 1     Creating library C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\iohook.lib and
   object C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\iohook.exp
⠹ Preparing native dependencies: 0 / 1  iohook.vcxproj -> C:\Users\User\Desktop\my-app\node_modules\iohook\build\Release\\iohook.node
✔ Preparing native dependencies: 1 / 1
✔ Launching Application

App threw an error during load
Error: Cannot find module 'C:\Users\User\Desktop\my-app\node_modules\iohook\builds\electron-v101-win32-x64\build\Release\iohook.node'
Require stack:
- C:\Users\User\Desktop\my-app\node_modules\iohook\index.js
- C:\Users\User\Desktop\my-app\src\index.js
- C:\Users\User\Desktop\my-app\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\User\Desktop\my-app\node_modules\iohook\index.js:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

Any ideas? Thank you very much...

**Comment by marcelblum** [comment]
I don't know why Forge is defaulting to trying to autobuild the module even if you already built it yourself and copied it over. But it may just be a path/folder structure issue, note that you need to place the build files under the path mentioned in the message where it's expecting to find it, `C:\Users\User\Desktop\my-app\node_modules\iohook\builds\electron-v101-win32-x64\build\Release\iohook.node`.

**Comment by jove0610** [comment]
It works now, thanks @marcelblum
