### ISSUE TITLE
how can import iohook into my web-application to get keyboard or mouse click event globally?

### ISSUE THREAD

**Issue by ZHENGYUN01** [wilix-team/iohook#411]
After a new development task assigned to me in which I need get keyboard and mouse click event globally and store it into a database, I search related work from google, then I found iohook may be suitable for me.

Unfortunately,

I install iohook package into my project, but I got some errors when i run the command `rush build`

error msg :

```
==[ FAILURE: 1 operation ]=====================================================

--[ FAILURE: demo ]---------------------------------[ 1 minute 56.3 seconds ]--

warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

warn  - Compiled with warnings

../../node_modules/iohook/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../libraries/keyboard/esm/keyboardListener.js
  ...3 lines omitted...

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (E:\demo\common\temp\node_modules\.pnpm\next@12.1.6_react-dom@17.0.2+react@17.0.2\node_modules\next\dist\compiled\jest-worker\index.js:1:12037)
    at ChildProcessWorker._onExit (E:\demo\common\temp\node_modules\.pnpm\next@12.1.6_react-dom@17.0.2+react@17.0.2\node_modules\next\dist\compiled\jest-worker\index.js:1:12975)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
```

anyone can help me out?

**Comment by ZHENGYUN01** [comment]
Any related IT-ers here?
