### ISSUE TITLE
Non-existing version of iohook, v0.9.3-node-v111-win32-x64

### ISSUE THREAD

**Issue by OguzhanUmutlu** [wilix-team/iohook#432]
NPM is failing to install iohook.

## Expected Behavior

Successful installation.

## Current Behavior

Throws an error:
```
npm ERR! command C:\windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Downloading prebuild for platform: iohook-v0.9.3-node-v111-win32-x64
Downloading prebuild.tar.gz                                                                                                                                                             
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.3/iohook-v0.9.3-node-v111-win32-x64.tar.gz returned 404                                                 
npm ERR! Prebuild for current platform (iohook-v0.9.3-node-v111-win32-x64) not found!
npm ERR! Try to build for your platform manually:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run build
npm ERR!
npm ERR! C:\Users\HP\IdeaProjects\neet\node_modules\iohook\install.js:16
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, open 'C:\Users\HP\AppData\Local\Temp\prebuild.tar.gz'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\HP\\AppData\\Local\\Temp\\prebuild.tar.gz'
npm ERR! }
```

## Possible Solution

An update

## Your Environment

Windows 11
HP Victus

- IOHook Version: 0.9.3
- Environment name and version: Node 19.8.1
- Operating System and version: Desktop, Windows 11

**Comment by dev-bre** [comment]
any update on this matter? is this lib still maintained?

**Comment by 277584579** [comment]
me too

**Comment by CyberLifeDev-Thomas** [comment]
i have the same problem, i was trying to install it, but then i've got this message : 

```
npm ERR! Downloading prebuild for platform: iohook-v0.9.3-node-v111-win32-x64
Downloading prebuild.tar.gz
npm ERR! Error: GET https://github.com/wilix-team/iohook/releases/download/v0.9.3/iohook-v0.9.3-node-v111-win32-x64.tar.gz returned 404
npm ERR! Prebuild for current platform (iohook-v0.9.3-node-v111-win32-x64) not found!
npm ERR! Try to build for your platform manually:
npm ERR! # cd node_modules/iohook;
npm ERR! # npm run build
npm ERR!
npm ERR! C:\Users\t.pierson\Documents\test\node_modules\iohook\install.js:16
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, open 'C:\Users\TE051~1.PIE\AppData\Local\Temp\prebuild.tar.gz'] {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Users\\TE051~1.PIE\\AppData\\Local\\Temp\\prebuild.tar.gz'
npm ERR! }
npm ERR!
npm ERR! Node.js v19.3.0
```

Then i've got an idea, so i try to download the v88 and rename it 'prebuild.tar.gz' and put it in 'C:\Users\TE051~1.PIE\AppData\Local\Temp\prebuild.tar.gz'. The installation proced well. 

Then i try to start it, and i've got a message from node :

```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 2 layouts.
refresh_locale_list [493]: Received 2 locales.
load_input_helper [866]: refresh_locale_list() found 2 locale(s).
node:internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\anonymous\Documents\test\node_modules\iohook\builds\node-v111-win32-x64\build\Release\iohook.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 111. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\anonymous\Documents\test\node_modules\iohook\index.js:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v19.3.0
```
So then i removed it and decided to repeat the same action but this time with the 'Source code
(tar.gz)'.
I've got this :

```
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'C:\Users\anonymous\Documents\test\node_modules\iohook\builds\node-v111-win32-x64\build\Release\iohook.node'
Require stack:
- C:\Users\anonymous\Documents\test\node_modules\iohook\index.js
- C:\Users\anonymous\Documents\test\record_2.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\anonymous\Documents\test\node_modules\iohook\index.js:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\anonymous\\Documents\\test\\node_modules\\iohook\\index.js',
    'C:\\Users\\anonymous\\Documents\\test\\record_2.js'
  ]
}

Node.js v19.3.0
```

In the directory 'iohook\builds\node-v111-win32-x64', there is no directory name build. There's only one directory name 'iohook-0.9.3'. I can't find the good file for the 'build\Release' directory. But i know that this files are the one that is in 'iohook-v0.9.3-node-v111-win32-x64.tar.gz'. . . 

can't go further. . .

I need to install it fast, i've got to use it fast before i get fired lmao
